//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financiera.WSFinanciera {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amortizacion", Namespace="http://schemas.datacontract.org/2004/07/WSFinanciera")]
    [System.SerializableAttribute()]
    public partial class Amortizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double abonoKsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double interesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int periodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double saldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double abonoKs {
            get {
                return this.abonoKsField;
            }
            set {
                if ((this.abonoKsField.Equals(value) != true)) {
                    this.abonoKsField = value;
                    this.RaisePropertyChanged("abonoKs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cuota {
            get {
                return this.cuotaField;
            }
            set {
                if ((this.cuotaField.Equals(value) != true)) {
                    this.cuotaField = value;
                    this.RaisePropertyChanged("cuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double interes {
            get {
                return this.interesField;
            }
            set {
                if ((this.interesField.Equals(value) != true)) {
                    this.interesField = value;
                    this.RaisePropertyChanged("interes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                if ((this.periodoField.Equals(value) != true)) {
                    this.periodoField = value;
                    this.RaisePropertyChanged("periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSFinanciera.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCuota", ReplyAction="http://tempuri.org/IService1/getCuotaResponse")]
        double getCuota(double monto, int plazo, double interes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCuota", ReplyAction="http://tempuri.org/IService1/getCuotaResponse")]
        System.Threading.Tasks.Task<double> getCuotaAsync(double monto, int plazo, double interes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTabla_Amortizacion", ReplyAction="http://tempuri.org/IService1/getTabla_AmortizacionResponse")]
        Financiera.WSFinanciera.Amortizacion[] getTabla_Amortizacion(double monto, int plazo, double interes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTabla_Amortizacion", ReplyAction="http://tempuri.org/IService1/getTabla_AmortizacionResponse")]
        System.Threading.Tasks.Task<Financiera.WSFinanciera.Amortizacion[]> getTabla_AmortizacionAsync(double monto, int plazo, double interes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Financiera.WSFinanciera.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Financiera.WSFinanciera.IService1>, Financiera.WSFinanciera.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getCuota(double monto, int plazo, double interes) {
            return base.Channel.getCuota(monto, plazo, interes);
        }
        
        public System.Threading.Tasks.Task<double> getCuotaAsync(double monto, int plazo, double interes) {
            return base.Channel.getCuotaAsync(monto, plazo, interes);
        }
        
        public Financiera.WSFinanciera.Amortizacion[] getTabla_Amortizacion(double monto, int plazo, double interes) {
            return base.Channel.getTabla_Amortizacion(monto, plazo, interes);
        }
        
        public System.Threading.Tasks.Task<Financiera.WSFinanciera.Amortizacion[]> getTabla_AmortizacionAsync(double monto, int plazo, double interes) {
            return base.Channel.getTabla_AmortizacionAsync(monto, plazo, interes);
        }
    }
}
